# Multi-Scale Modelling of Biological Systems Computer Practical 4 - Part I

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
model1 = np.array([
    [0.971, 0.04, -0.046, 0.141, -0.159],
    [0.988, 0.017, -0.068, 0.073, -0.131],
    [0.102, 0.155, 0.973, -0.084, 0.09],
    [0.089, 0.992, -0.031, -0.067, -0.072],
    [0.144, 0.975, -0.027, -0.061, -0.142],
])

model2 = np.array([
    [-0.267, -0.215, -0.032, -0.088, -0.189, -0.895, -0.175],
    [0.113, 0.293, 0.401, 0.783, -0.137, -0.26, -0.097],
    [0.932, -0.072, -0.073, -0.188, 0.236, 0.079, 0.089],
    [0.067, -0.087, 0.185, -0.157, -0.179, 0.122, 0.955],
    [-0.13, -0.115, -0.076, -0.042, -0.094, -0.083, -0.979],
])

brain = np.array([
    [0.981, -0.066, -0.045, -0.14, 0.058, 0.005, 0.06, -0.016, -0.095],
    [0.974, -0.042, -0.055, -0.179, 0.05, 0.049, 0.014, 0.035, -0.087],
    [0.1, 0.138, 0.96, -0.084, 0.089, -0.022, -0.096, -0.079, -0.145],
    [0.051, 0.99, -0.099, -0.016, 0.003, -0.067, -0.032, -0.003, -0.086],
    [0.077, 0.986, -0.094, -0.042, 0.013, -0.067, -0.036, -0.037, -0.097],
])

In [3]:
def calculate_distance_matrix(model: np.ndarray) -> np.ndarray:
    """
    Calculate the distance matrix for a given model.

    Parameters:
    model (np.ndarray): The input model as a 2D numpy array.

    Returns:
    np.ndarray: The distance matrix as a 2D numpy array.
    """
    num_rows = model.shape[0]
    distance_matrix = np.zeros((num_rows, num_rows))

    for i in range(num_rows):
        for j in range(num_rows):
            distance_matrix[i, j] = np.linalg.norm(model[i] - model[j])

    return distance_matrix

In [5]:
# Print distance matrices for the models
rdm_model1 = calculate_distance_matrix(model1)
rdm_model2 = calculate_distance_matrix(model2)
rdm_brain = calculate_distance_matrix(brain)
print("Distance Matrix for Model 1:\n", rdm_model1)
print("Distance Matrix for Model 2:\n", rdm_model2)
print("Distance Matrix for Brain:\n", rdm_brain)

Distance Matrix for Model 1:
 [[0.         0.08191459 1.38541438 1.31730255 1.2647561 ]
 [0.08191459 0.         1.40043243 1.33539357 1.28446798]
 [1.38541438 1.40043243 0.         1.31730293 1.31473077]
 [1.31730255 1.33539357 1.31730293 0.         0.09091755]
 [1.2647561  1.28446798 1.31473077 0.09091755 0.        ]]
Distance Matrix for Model 2:
 [[0.         1.32687867 1.63362419 1.57831524 1.16086433]
 [1.32687867 0.         1.50337919 1.52681499 1.39454975]
 [1.63362419 1.50337919 0.         1.31909249 1.55781449]
 [1.57831524 1.52681499 1.31909249 0.         1.9775098 ]
 [1.16086433 1.39454975 1.55781449 1.9775098  0.        ]]
Distance Matrix for Brain:
 [[0.         0.09501053 1.36507619 1.41959536 1.39742442]
 [0.09501053 0.         1.36767979 1.40167186 1.37996087]
 [1.36507619 1.36767979 0.         1.37010365 1.35933145]
 [1.41959536 1.40167186 1.37010365 0.         0.05278257]
 [1.39742442 1.37996087 1.35933145 0.05278257 0.        ]]


In [6]:
# Calculate similarity between the models and the brain using the Pearson Correlation Coefficient
def calculate_similarity(rdm1: np.ndarray, rdm2: np.ndarray) -> float:
    """
    Calculate the similarity between two distance matrices using the Pearson Correlation Coefficient.

    Parameters:
    rdm1 (np.ndarray): The first distance matrix.
    rdm2 (np.ndarray): The second distance matrix.

    Returns:
    float: The Pearson Correlation Coefficient between the two distance matrices.
    """
    # Flatten the upper triangular part of the distance matrices to avoid redundancy
    rdm1_flat = rdm1[np.triu_indices_from(rdm1, k=1)]
    rdm2_flat = rdm2[np.triu_indices_from(rdm2, k=1)]

    # Calculate the Pearson Correlation Coefficient.
    correlation_coefficient = np.corrcoef(rdm1_flat, rdm2_flat)[0, 1]
    
    return correlation_coefficient

In [7]:
PCC_model1_brain = calculate_similarity(rdm_model1, rdm_brain)
PCC_model2_brain = calculate_similarity(rdm_model2, rdm_brain)
print(f"Pearson Correlation Coefficient between Model 1 and Brain: {PCC_model1_brain:.4f}")
print(f"Pearson Correlation Coefficient between Model 2 and Brain: {PCC_model2_brain:.4f}")

Pearson Correlation Coefficient between Model 1 and Brain: 0.9951
Pearson Correlation Coefficient between Model 2 and Brain: -0.3805


Model 1 is the better fit, because it has a very high Pearson Correlagtion Coefficient (whereas the Pearson Correlation Coefficient of model 2 is way lower). If you look at the matrices, you can also see why this is the case, because if you look at where the high and low values are located, the matrices of model 1 and the brain look quite similar. In contrast, the matrix for model 2 has high values at locations where the brain has low values, for example.